### ISSUE TITLE
26 January 2024 - TraderX Meeting Agenda

### ISSUE THREAD

**Issue by maoo** [finos/traderX#101]
## Date
26 January 2024 - 8 am EST / 1 pm GMT

## Previous Meeting
[12 January 2024 - TraderX Meeting Agenda](https://github.com/finos/traderX/issues/93)

## Untracked attendees 
- 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes ( #79 )
- [ ] Introductions
- [ ] Internal corporate adoption/development of TraderX
- [ ] Review Priority issues
- [ ] Hack day opportunities
- [ ] AOB, Q&A & Adjourn (5mins)

## Discussed Points
- @rocketstack-matt is working on a PR with K8S manifests
- For now, we can use an EC2 instance that runs Docker Compose; the instance will reboot and reset the dataset every 24 hours. 
- We discussed aspirational roadmap; @mimiflynn suggested a (git-)branching model which allows to implement different use cases of traderx, or use them to run hackathons.
- @karlmoll suggested to connect with Devops Automation
- @ctiltman suggested the use of Architecture as Code in TraderX

## Actions
- [x] @maoo restarts the existing EC2 instance and updates to the latest traderx version ; the team can review the endpoint when ready
- [x] @rocketstack-matt raises PR with K8S manifests
- [x] @karlmoll reaches out to Devops Automation

### Zoom Details
- https://zoom.us/j/96264933811?pwd=d2VmSkdudDRXZytPclBRblc4eUlEZz09
- **Meeting ID:** 962 6493 3811
- **Passcode:** 532953

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by maoo** [comment]
@maoo / FINOS

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by ctiltman** [comment]
Cliff Tiltman - Morgan Stanley

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by rocketstack-matt** [comment]
Draft PR as discussed in todays meetup - https://github.com/finos/traderX/pull/102
