### ISSUE TITLE
23 February 2024 - TraderX Meeting Agenda

### ISSUE THREAD

**Issue by DovOps** [finos/traderX#121]
## Date
23 February 2024 - 8 am EST / 1 pm GMT

## Previous Meeting
[9 February 2024 - TraderX Meeting Agenda](https://github.com/finos/traderX/issues/113)

## Untracked attendees 
- 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes ( #113  )
- [x] Introductions
- [ ] Internal corporate adoption/development of TraderX
- [ ] Review Priority issues
- [ ] Hack day opportunities
- [ ] AOB, Q&A & Adjourn (5mins)

## Discussed Points
 - Demo instance
   - @maoo  provided an update on the live environment.  It's now up at https://demo.traderx.finos.org
   - This is not a 'prod-grade' instance/environment, but it's great as a live demo instanc
   - This was the initial response for #29 
   - Next Steps
     - Free up traderx.finos.org for use as the documentation microsite 
     - Basic GUI / UX enhancement
  - Monitoring/Uptime/Status page
    - Could be a good first issue to build 'readiness endpoints' into each service to report uptime/service status
    - @maoo  suggested uptime robot which could be used 
    - @rocketstack-matt  has #102  which could be helpful
  - One idea - Share journey (Docker/K8S) on this with the devops automation SIG. Perhaps worth getting them involved - (Worth raising with Amol )
  - @rocketstack-matt  - in Architecture as Code SIG - they modeled TraderX as a sample application. This is also a nice synergy.  
    

## Actions
- [x] Close all previous meeting issues in GitHub. 
- [x] use demo.traderx.finos.org as domain name
- [x] follow notes on https://github.com/finos/traderX/pull/114/files - cherry pick changes and apply to the `ingress-container` branch
- [x] @maoo to apply changes on live environment and notify team
- [ ] Arch as Code SIG to open issue to update C4 to include nginx. ( @rocketstack-matt  )

### Zoom Details
- https://zoom.us/j/96264933811?pwd=d2VmSkdudDRXZytPclBRblc4eUlEZz09
- **Meeting ID:** 962 6493 3811
- **Passcode:** 532953

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by heswell** [comment]
Steve Heron / UBS

**Comment by DovOps** [comment]
@maoo  - Just a follow-up question I forgot to ask you on the call.  The hosted environment - how is it deployed? How often is it paved over ?

**Comment by maoo** [comment]
> @maoo - Just a follow-up question I forgot to ask you on the call. The hosted environment - how is it deployed? How often is it paved over ?

There's a cron that runs once a day, which pulls and re-runs `docker-compose up` , see https://gist.github.com/maoo/51aef572973456437e28748200149126#file-deploy-traderx-sh
