### ISSUE TITLE
22 March 2024 - TraderX Meeting Agenda

### ISSUE THREAD

**Issue by DovOps** [finos/traderX#141]
## Date
22 March 2024 - 8 am EST / 12 pm GMT

## Previous Meeting
[8 March 2024 - TraderX Meeting Agenda](https://github.com/finos/traderX/issues/128)

## Untracked attendees 
- Maria Lopatkova (SmoothStack)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes ( #128 )
- [x] Introductions
- New issues
  - [x] #133 
  - [x] #132 
  - [ ] #131 
  - [x] #130 
- [ ] FDC3 Hackathon end of Q2 (@maoo )
- [ ] Milestones review (add issues to milestones)
- [ ] AOB, Q&A & Adjourn (5mins)

## Discussed Points 
 - @psmulovics  - raised opportunity to create a cross-project milestone (E.g. for OSSF June/LN, or OSSF Nov /NY) for tracking things we want to get done by the events.
 - Reviewed #133 - Agreed it's not top priority but good opportunity for outside contribution.
 - Discussed http://app.moderne.io - and updating FINOS (not just TraderX) code using OpenRewrite recipes. NOTE: I had Moderne add the whole FINOS org to their list of open source orgs they keep ready for analysis and modification.
 - Discussed CDM/TraderX - integration / experiments. 

## Next Steps:
  - Add C4 Diagram thumbnail and other architecture/flow links to main README as an interim step for enhanced documentation (Open a new issue)
  - @tomhealey-icma and @maoo  to explore integrating CDM/TraderX in a branch environment - for #140 
  - @rocketstack-matt  - in Architecture as Code SIG - What are the next steps?
  - Solicit volunteers to build the website/Documentation / #133 
  - @psmulovics  discovered that the .NET code for People Service is not up to date. Will create an issue to update it.
    

### Zoom Details
- https://zoom.us/j/96264933811?pwd=d2VmSkdudDRXZytPclBRblc4eUlEZz09
- **Meeting ID:** 962 6493 3811
- **Passcode:** 532953

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by ctiltman** [comment]
Clifford Tiltman - Morgan Stanley

**Comment by DovOps** [comment]
Dov Katz - Morgan Stanley

**Comment by maoo** [comment]
@maoo / FINOS

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by karlmoll** [comment]
Karl Moll / FINOS
