### ISSUE TITLE
Cannot login to H2 Console

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/traderX#152]
## Bug Report

After building and launching the database I tried to run the H2 console. The login popup works but I'm getting a error:

[IO Exception: "/home/acpvst3/test outside [my path]traderX/database/_data" [90028-224]](http://localhost:18084/login.do?jsessionid=c3758cd4caa25d9b8a47d93760771540#) 90028/90028 [(Help)]

This does not affect connecting from the account-service which works correctly.

### Steps to Reproduce:
 1. Follow the instructions to build and run the database, https://github.com/finos/traderX/tree/main/database.
 2. Open Browser and enter localhost:18084
 3. Enter pw and click Connect or Test
 4. You can also run the same process in powershell without bash and get the same error.

### Expected Result:
H2 Console 

### Actual Result:
[IO Exception: "/home/acpvst3/test outside /mnt/d/IdeaProjects/finos/traderx/traderx-cdm4/traderX/database/_data" [90028-224]](http://localhost:18084/login.do?jsessionid=862cb9692cf89f1f2111b65c85409477#) 90028/90028 [(Help)]

### Environment:
Windows 10
Gradle 8.4
Java 17
Bash or Powershell will result in same error

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

**Comment by DovOps** [comment]
@tomhealey-icma  - In the login console, did you specify your database url as **jdbc:h2:./traderx**  and username/password both the same?

I'll update the README

**Comment by tomhealey-icma** [comment]
Resolved
