### ISSUE TITLE
Ignore updates outside of website and docs folder from Netlify

### ISSUE THREAD

**Issue by maoo** [finos/traderX#157]
Please configure Netlify so that it will trigger preview builds only when `docs/**` or `website/**` are updated.

**Comment by TheJuanAndOnly99** [comment]
This is part of the Docusaurus PR. See https://github.com/finos/traderX/pull/138/files#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489edR1

**Comment by maoo** [comment]
Awesome, thanks @TheJuanAndOnly99 !
