### ISSUE TITLE
Windows 10 Support

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/traderX#95]
I've been trying to build and run on Windows but getting various errors:
 => CANCELED [account-service 4/4] RUN ./gradlew build                                                                                                          1.0s
------
 > [position-service 4/4] RUN ./gradlew build:
0.917 /bin/sh: 1: ./gradlew: not found
------
failed to solve: process "/bin/sh -c ./gradlew build" did not complete successfully: exit code: 127

Notes:
Docker is running
./gradlew build works from inside each service directory but fails from the scripts
Java 17

I may need to debug the setup but wanted to first if anyone else is running on Windows?

**Comment by DovOps** [comment]
@rocketstack-matt  may be able to troubleshoot here, as he created the docker config

**Comment by rocketstack-matt** [comment]
I don't have a Win 10 machine to test on, but from a little research this may be caused by line endings in the gradle file when building in WSL.

@tomhealey-icma I'm assuming you're running in WSL? Can you please try the setting the following git config `git config --global core.autocrlf input` delete the local repo and re-clone, then try the docker build again.

**Comment by rocketstack-matt** [comment]
I was able to replicate this issue with an Azure VM

> [!NOTE]
> Win10 Pro running on a Standard E4s v3 (4 vcpus, 32 GiB memory)
> git version 2.43.0.windows.1
> java 21.0.2 2024-01-16 LTS

I cloned the traderx repo and ran `docker compose up` from the root, result was:

>  => [position-service 3/4] COPY . .                                                                                                                                                                            0.9s
>  => ERROR [position-service 4/4] RUN ./gradlew build                                                                                                                                                           1.6s
> ------
>  > [position-service 4/4] RUN ./gradlew build:
> 0.754 /bin/sh: 1: ./gradlew: not found
> ------
> failed to solve: process "/bin/sh -c ./gradlew build" did not complete successfully: exit code: 127

I deleted the cloned repo and ran the command I suggested previously `git config --global core.autocrlf input` then re-cloned the repo and re-ran `docker compose up`. This worked to build all the images but the *database* container failed to start, unable to find `run.sh`. This was related to the execute permission having been lost, I have updated the [Dockerfile in this PR](https://github.com/finos/traderX/pull/99) for the database to explicitly  `chmod +x` the script which then worked.
